TRAINING:
  estimateMissingObjects: true
  highestQuantisationBinCentre: 0.1
  lossType: crossEntropy
  lowestQuantisationBinCentre: 0.001
  numberOfQuantisationBins: 6
  predictionQuantity: finalDisplacement
  predictionScale: object
  useGradientPenalty: true
name: crossEntropy_object_missing